environment:
  matrix:
    - nodejs_version: '16'

version: '{build}'

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm install

test_script:
  - pnpm test
  - pnpm run coverage

build: off
deploy: off
